### ISSUE TITLE
dev Perl build hangs on Travis

### ISSUE THREAD

**Issue by calid** [travis-perl/helpers#15]
Hello, I'm not sure this is an issue with travis-perl-helpers or Travis infra itself, but the `dev` Perl consistently hangs and errors out for me on Travis.  See https://travis-ci.org/calid/zmq-ffi/jobs/53009125 for an example.

I've rerun several times now throughout the day but always with the same result.  I have no issues with the other Perls.

Thanks!

**Comment by autarch** [comment]
I suspect this can be closed. It sounds like it was an error with that particular dev version of Perl.

**Comment by djzort** [comment]
May as well close this
