### ISSUE TITLE
build-dist uses $MODERN_PERL rather than current Perl version for EU::MM and M::B

### ISSUE THREAD

**Issue by zmughal** [travis-perl/helpers#17]
`build-dist` should use current Perl version rather than always using `$MODERN_PERL` when calling `perl Makefile.PL` or `perl Build.PL`.

This more accurately reflects how a user would install from CPAN. We came across this when using the helpers on PDL (which just uses EU::MM).

@mohawk2

**Comment by zmughal** [comment]
Ah, I see why this runs as it does now. This simulates the author creating a new dist for CPAN. Perhaps two passes of running the build script might be a cleaner solution for some dists?

**Comment by haarg** [comment]
The basic idea of running build-dist with a different perl is extremely intentional.  build-dist is the part that would normally be run by the author.  The documentation is possibly not where it should be though.

What actual problem did you run into here?

**Comment by mohawk2** [comment]
I can see the `$MODERN_PERL` concept is critical for transforming dzil author-side into install-side so the tests etc run. However, the situation PDL faces is it uses EUMM and the deps are expressed by either having a `META.*` (which isn't in the repo) or in `Makefile.PL` (which relies on all the `CONFIGURE_REQUIRES` being there).

What we did in the `.travis.yml` was eg `cpanm Alien::HDF4`, but that goes into the build-time perlbrew, not the configure-time one. Is there an idiomatic way to make things available to the configure-time one?

**Comment by zmughal** [comment]
Thanks!

Disabling the split build (with `SPLIT_BUILD=0`) is the solution I went with [here](https://github.com/PDLPorters/pdl/pull/71). It works beautifully! :-)

**Comment by mohawk2** [comment]
Doing `SPLIT_BUILD=0 build-dist` didn't change anything, which is regrettable.
