### ISSUE TITLE
Do not use sudo

### ISSUE THREAD

**Issue by oschwald** [travis-perl/helpers#21]
`sudo` does not work with the newer [Travis container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/). By using sudo, the builds are forced to use the older system, which [is overwhelmed](https://www.traviscistatus.com), causing very slow builds.

**Comment by haarg** [comment]
The only place that the helpers will use sudo is to attempt to install OS packages that are needed for some modules.  There isn't really anything I can replace that with inside the helpers, and if it fails, installation will continue.  The example text in the README includes "sudo: false".

So I don't really see anything that I could change to improve things.

**Comment by oschwald** [comment]
Thanks. I'll close this. I missed the example with `sudo: false`.
