### ISSUE TITLE
Isolate build-requires from requires and test-requires

### ISSUE THREAD

**Issue by preaction** [travis-perl/helpers#29]
I have no idea if this is appropriate for these helpers, but I just released a module (Statocles) with a missing dependency entry (List::UtilsBy), but my travis configuration didn't make a peep. My current working theory is that some part of my build chain installs that module (Dist::Zilla::Plugin::Git::Contributors looks the likely suspect).

If this could somehow isolate those modules (`cpanm -l buildlib` perhaps?), it might prevent this problem.

**Comment by haarg** [comment]
1. There are a number of modules that are preinstalled by Travis.  If you are using a perl version provided by Travis, you will get those preinstalled versions.  If you specify a full three part version (5.20.1), Travis will never provide it.  For versions like these that the helpers either build or download, there aren't any preinstalled non-core versions.
2. There is a local-lib helper command that will create and activate a new local::lib directory.  This can help you isolate different parts of the build process.
3. The build-dist helper command (which is used by --auto) installs dist build prereqs in an isolated local::lib, which won't be active during future testing phases.  So any prereqs installed as part of the Dist::Zilla build phase won't be available during the configure/build/test phases.  This is controllable via the SPLIT_BUILD env variable, in case it isn't wanted.

These things combined mean that if you use a full three part perl version, the configure/build/test phases should start from a pristine perl install, without any non-core dependencies.

I know that this isn't entirely clear from the documentation.  Aside from the usual issues of being too close to the code, I also was never sure what my audience would be when writing them.  If you have any suggestions I would welcome them.

**Comment by preaction** [comment]
1. Sigh... another vendor mucking about with the core perl distribution...
2. Okay
3. Ah, okay, so `local-lib`, given no args, will create a new local::lib (with a randomized name) using mktemp. And the entirety of `build-dist` runs in that new local::lib's scope. So... Yeah... Then it must be Travis doing it...

Okay, so I'll add one Perl version to my list of versions that is a 3-part version to get a pristine copy. That should better reveal missing deps.

Sorry about the spurious report. Thanks for the help!

**Comment by preaction** [comment]
And then it turns out that the bundled versions were also hiding an _entirely different_ bug in my prereqs... https://github.com/preaction/Statocles/commit/06f649854daec58c2f1e5fef48e5e1bcad519ccd

Thanks again!
