### ISSUE TITLE
What does `local-lib` with no args do?

### ISSUE THREAD

**Issue by schwern** [travis-perl/helpers#37]
I understand what local::lib is, but I don't understand it's utility wrt Travis.

The docs say:

> Activates a local::lib directory. Without a parameter, creates a new local::lib directory and activates it. Any parameters given are taken as names of predefined local::libs.

The predefined part I get, `- local-lib dzil` means I get prebuilt Dist::Zilla.

What does just `- local-lib` do for me? Why would I use it? Should I be using it?

**Comment by haarg** [comment]
It creates a new local::lib where any future installs will go to.  This can be valuable if you need to isolate the prereqs you are installing from the core modules.  This is something I personally needed, but probably not often required.
