### ISSUE TITLE
Blead can not be built with travis-provided perlbrew

### ISSUE THREAD

**Issue by ribasushi** [travis-perl/helpers#44]
There seems to be no ticket about this so adding an entry with all the snippets in one place.

A [minimal .travis.yml like this](https://github.com/ribasushi/travis_helpers_minimal_demo/commit/388ce974#diff-354f30a63fb0907d4ad57269548329e3) will currently [fail to build blead](https://travis-ci.org/ribasushi/travis_helpers_minimal_demo/jobs/197624003#L198).

The underlying error is likely the same as what can be seen in the [DBIC setup](https://travis-ci.org/ribasushi/dbix-class/jobs/190905658#L454-L464).

Which in turn is a side-effect of https://github.com/gugod/App-perlbrew/issues/523 and specifically https://github.com/gugod/App-perlbrew/pull/524#issuecomment-261051882.

I have not investigated as of yet how to cleanly update perlbrew on travis before running the helper. It is even possible that the helpers have a way of addressing this, but if that is the case it does not happen automatically, and is not mentioned [within the corresponding manual section](https://github.com/travis-perl/helpers#example-long-travisyml)

If a user-side upgrade is even possible, ideally it should be automatic... Thoughts?

**Comment by ribasushi** [comment]
@haarg: hold fire on this: this problem is likely a completely different animal.
The day I decided to test all this [is the day p5p's SSL expired](https://www.ssllabs.com/ssltest/analyze.html?d=perl5.git.perl.org)...

**Comment by ribasushi** [comment]
@haarg ok, now that the certificate is fixed, the error I outlined in https://github.com/travis-perl/helpers/issues/44#issue-204862419 is still present. This ticket is now "valid".

**Comment by theory** [comment]
Seeing the same issue with [Sqitch blead builds](https://travis-ci.org/theory/sqitch/jobs/236427809). :-(

**Comment by wbraswell** [comment]
@ribasushi 
Is this the same reason why my attempt to build blead fails with only a "compilation failed?" error message?
https://travis-ci.org/wbraswell/rperl/jobs/242922708

**Comment by ribasushi** [comment]
@wbraswell yes, same issue. What needs to happen is the travis-provided perlbrew needs to get upgraded somehow. If I were @haarg I'd handle it from within the helpers themselves.

**Comment by autarch** [comment]
Looks this is fixed. Close it?

**Comment by wbraswell** [comment]
@ribasushi 
I see now that "blead" is passing on my latest RPerl code, does that mean this issue is 100% resolved and can be closed?

**Comment by ribasushi** [comment]
@haarg the travis-supplied perlbrew is still at [`0.73`](https://travis-ci.org/Perl5/DBIx-Class/jobs/346651941#L425). AFAIK this is not sufficient to address all of the issues above. Did `travis-perl` start auto-upgrading `perlbrew` in the meantime? If yes - please close this ticket

**Comment by wbraswell** [comment]
Now I can not install blead:

https://api.travis-ci.org/v3/job/358533963/log.txt

```
$ perlbrew use blead
blead is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-blead.tar.bz2
$ sudo tar xjf perl-blead.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

ERROR: The installation "blead" is unknown.
```

When I try to run the download myself:

```
$ wget https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-blead.tar.bz2
--2018-03-26 15:04:15--  https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-blead.tar.bz2
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.18.123
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.18.123|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-26 15:04:17 ERROR 404: Not Found.
```

So what's really going on here?  Is this one problem or a bunch of different problems mixed together?!?

**Comment by wbraswell** [comment]
@haarg 
Yes I saw that Perl v5.27 was getting built but I was confused by all the errors.
Can you please give me a little bit more information about why I am having errors at all?
