### ISSUE TITLE
production version aliases?

### ISSUE THREAD

**Issue by FGasper** [travis-perl/helpers#56]
It would be nice to have able to say, “test against all Perl versions” without having to spell out each version manually.

There doesn’t seem to be any documented way to do this … would it work to allow something like:
```
perl: all
```
??

**Comment by kjetilk** [comment]
Like, you'd like to test against the output of 
```
perlbrew available 
```
? 

That's quite a lot of CPU time, what would it achieve? Personally, I think cpantesters give a better picture of the breath of the ecosystem, travis is more for rapid feedback, but that's just me.

**Comment by haarg** [comment]
This would require controlling the build matrix.  That is something done by Travis-CI.  The helpers only take effect after a build is started, and can't impact the matrix.

This isn't possible to do.
