### ISSUE TITLE
Tests run with wrong version of perl

### ISSUE THREAD

**Issue by DrHyde** [travis-perl/helpers#65]
Perl 5.28.0 is out now, so I tried adding it to the travis config for one of my modules. But 5.28 isn't yet available to travis, so it failed to download, perlbrew failed to switch versions - and then it continues on to run the tests, against what I presume is the system default perl.

Relevant snippets from the job log:

    5.28 is not installed; attempting download
    Downloading archive: https://s3.amazonaws.com/travis-perl- 
    archives/binaries/ubuntu/14.04/x86_64/perl-5.28.tar.bz2
    $ sudo tar xjf perl-5.28.tar.bz2 --directory /
    bzip2: (stdin) is not a bzip2 file.
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now

At this point it then continues on to do a git clone of my project, after which:

    $ perlbrew use 5.28
    ERROR: The installation "5.28" is unknown.
    $ perl --version
    This is perl 5, version 18, subversion 2 (v5.18.2) ...

The tests then run against perl 5.18.2. You can see all the details here: https://travis-ci.org/DrHyde/perl-modules-File-Overwrite/jobs/396597516

**Comment by haarg** [comment]
The tests did actually run against perl 5.28.0.  

https://travis-ci.org/DrHyde/perl-modules-File-Overwrite/jobs/396597516#L467

This is mentioned [in the docs](https://github.com/travis-perl/helpers#notes), although it could be clearer.  With the way travis and these helpers work, I can't do anything about the initial misleading version report.

**Comment by DrHyde** [comment]
Ahhh, OK, thanks.

Something else that's a bit unclear is `"/home/travis/perl5/perlbrew/perls/5.24.3/bin/perl" "-MExtUtils::Manifest=mkmanifest" -e mkmanifest` - yet another unexpected version of perl!
