### ISSUE TITLE
Historical dependencies from barnyard.co.uk can't be installed

### ISSUE THREAD

**Issue by choroba** [travis-perl/helpers#70]
The log of a [5.6 job](https://travis-ci.org/choroba/syntactic-construct/jobs/542027168) is full of failures like this one:
```
--2019-06-06 07:32:27--  (try: 6)  http://cp5.6.2an.barnyard.co.uk/authors/01mailrc.txt.gz
Connecting to cp5.6.2an.barnyard.co.uk (cp5.6.2an.barnyard.co.uk)|109.123.89.254|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 258079 (252K) [application/x-gzip]
Saving to: ‘STDOUT’
     0K                                                         0% 0.00 =0s
2019-06-06 07:32:28 (0.00 B/s) - Connection closed at byte 0. Retrying.
```
If fails after 45 minutes. Other jobs for other Perl versions finish in ~40 secs.

**Comment by choroba** [comment]
See also [#6](/MorayJ/cpXXXan/issues/6#issuecomment-499430274)

**Comment by pali** [comment]
I guess it was fixed by commit https://github.com/travis-perl/helpers/commit/080ddfa4bd4d7ed467e87203f1875e95c4c48780

**Comment by djzort** [comment]
May as well close this
