### ISSUE TITLE
Perls older than 5.22 don't download on Xenial

### ISSUE THREAD

**Issue by mienaikage** [travis-perl/helpers#71]
The files that Travis attempts to download for 5.20 and earlier have suddenly gone AWOL

https://storage.googleapis.com/travis-ci-language-archives/perl/binaries/ubuntu/16.04/x86_64/perl-5.20.tar.bz2

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: travis-ci-language-archives/perl/binaries/ubuntu/16.04/x86_64/perl-5.20.tar.bz2</Details></Error>
```

EDIT: This seems to be because the build I was using switched from Trusty to Xenial, Travis have bumped their default.

**Comment by mienaikage** [comment]
It looks like my OS on Travis has changed version since my last successful run, was using 14.04 before.

**Comment by srchulo** [comment]
I'm seeing this too:

https://travis-ci.org/srchulo/Mojolicious-Plugin-CanonicalURL

Everything older than 5.22 fails.

**Comment by oalders** [comment]
Does setting `dist: trusty` fix this?

**Comment by srchulo** [comment]
Sorry-- where should `dist: trusty` go?

**Comment by oalders** [comment]
You can add that as a top level key to your `.travis.yml`, but I'm wondering if this would "just work" for you if you update your `.travis.yml` to let the helpers do everything automatically. For example: https://github.com/oalders/open-this/blob/master/.travis.yml is passing on all Perls (except for some author tests I need to fix).

On a related note, you can automate some of your config set up using a CLI tool.  I wrote a blog post about it here: http://www.olafalders.com/2019/05/22/managing-your-travis-ci-config-files-with-appcisetup/

**Comment by srchulo** [comment]
@oalders Thanks for that! That CLI tool is super useful.

**Comment by oalders** [comment]
@srchulo you're welcome.  :)  I'm using it to manage most of my Travis config files now.  Saves me a lot of time.

**Comment by pali** [comment]
Hello!

I'm closing this issue as it is not relevant to travis-perl-helpers project. travis-perl-helpers is *unofficial* and enabled in .travis.yml by:
```
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
```

URL https://storage.googleapis.com/travis-ci-language-archives/perl/binaries/ubuntu/16.04/x86_64/perl-5.20.tar.bz2 comes from *official* travis and has nothing to do with travis-perl-helpers.

Problems related with https://storage.googleapis.com/travis-ci-language-archives  please report to Travis project iself: https://github.com/travis-ci/travis-ci

**Comment by mienaikage** [comment]
For future readers, discussion of the issue looks to be happening here: https://travis-ci.community/t/failure-with-perl-5-16-5-18-5-20/2458
