### ISSUE TITLE
cperl

### ISSUE THREAD

**Issue by tobyink** [travis-perl/helpers#80]
perlbrew supports cperl.

Does travis-perl support it?

**Comment by mohawk2** [comment]
Try it and see? I for one would be happy to accept PRs to fix any problems, but I won't be going out of my way for it.

**Comment by tobyink** [comment]
Seems to not work, but not a lot of information about why:
https://travis-ci.org/github/tobyink/p5-exporter-tiny/jobs/661262196

When I've used perlbrew and cperl on my local machine, I've found that to install it properly you need to do:

```
perlbrew install --notest cperl-5.30.0
ln -s $PERLBREW_ROOT/perls/cperl-5.30.0/bin/{cperl,perl}
```

Because `make install` installs the binary as "cperl" instead of "perl", and that makes `perlbrew list` unable to detect that the installation worked.

**Comment by mohawk2** [comment]
If that gets fixed in perlbrew, it will work without further effort here. I do not feel it a valuable activity for the limited capacity of travis-perl.

**Comment by tobyink** [comment]
I can build cperl on perlbrew fine now. I don't know whether my previous issues were due to a broken local installation of perlbrew, or an old version of perlbrew with limited cperl support, but I can confirm that perlbrew is currently able to handle cperl.

**Comment by mohawk2** [comment]
Glad to hear! Therefore will close this.
