### ISSUE TITLE
Add support for perl 5.32

### ISSUE THREAD

**Issue by DrHyde** [travis-perl/helpers#82]
I assume that this is as simple as building a tarball and uploading it, but right now I'm seeing build failures thus:

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/perl/binaries/ubuntu/14.04/x86_64/perl-5.32.tar.bz2
curl: (22) The requested URL returned error: 404 Not Found
$ sudo tar xjf perl-5.32.tar.bz2 --directory /
tar (child): perl-5.32.tar.bz2: Cannot open: No such file or directory
```

followed by things getting terribly confused as perlbrew (obviously) fails to switch versions, and then things fail to load from `/home/travis/perl5/perlbrew/perls/5.32/...` and so on.

**Comment by DrHyde** [comment]
Here's a failing build https://travis-ci.com/github/DrHyde/perl-modules-Test-Mojo-Role-HTTPstatus/jobs/386680816

**Comment by tobyink** [comment]
I've been using Perl 5.32 in my tests for a while and it's mostly okay. I get sporadic issues with the threaded version of it, I think related to a broken module on the Travis servers. Usually waiting a couple of hours and re-running that build solves it though.

https://travis-ci.org/github/tobyink/p5-type-tiny includes eight Perl 5.32 tests (two threaded and six non-threaded).

**Comment by tobyink** [comment]
Also, I note you're using "trusty" as your Linux distribution. Maybe try using "xenial" for Perl 5.28+ and just use "trusty" for older versions.

**Comment by DrHyde** [comment]
Ah-ha, yes, switching to xenial for modern perl versions fixed it. Thanks!
